pipeline {
    agent any
    tools {
    maven 'Maven3'
    jdk 'Java11'
}


    environment {
        CHROME_BIN = '/usr/bin/google-chrome'
        CHROMEDRIVER_BIN = '/usr/local/bin/chromedriver'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/TanujaMarni/automatic-testing.git'
            }
        }

        stage('Install Chrome & Chromedriver') {
            steps {
                sh '''
                    sudo apt-get update
                    sudo apt-get install -y google-chrome-stable unzip xvfb
                    wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
                    unzip chromedriver_linux64.zip
                    sudo mv chromedriver /usr/local/bin/
                    sudo chmod +x /usr/local/bin/chromedriver
                '''
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
        success {
            echo 'Tests passed!'
        }
        failure {
            echo 'Some tests failed.'
        }
    }
}
